### ISSUE TITLE
Multiple tests failling

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-output-redis#49]
https://travis-ci.org/logstash-plugins/logstash-output-redis/builds/236452094

```
  1) LogStash::Outputs::Redis Redis#receive in batch mode should call buffer_receive
     Failure/Error: expect{redis.receive(event)}.to_not raise_error
     
       expected no Exception, got #<RSpec::Mocks::MockExpectationError: (<LogStash::Outputs::Redis key=>"thekey", data_type=>"list", ba...timestamp\":\"2017-05-27T04:20:40.423Z\",\"@version\":\"1\",\"message\":\"test\"}"], "thekey", nil)> with backtrace:
         # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/stud-0.0.22/lib/stud/buffer.rb:221:in `block in buffer_flush'
         # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'
         # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'
         # ./lib/logstash/outputs/redis.rb:236:in `send_to_redis'
         # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-codec-json-3.0.2/lib/logstash/codecs/json.rb:42:in `encode'
         # ./lib/logstash/outputs/redis.rb:150:in `receive'
         # ./spec/unit/outputs/redis_spec.rb:35:in `block in /home/travis/build/logstash-plugins/logstash-output-redis/spec/unit/outputs/redis_spec.rb'
         # ./spec/unit/outputs/redis_spec.rb:35:in `block in /home/travis/build/logstash-plugins/logstash-output-redis/spec/unit/outputs/redis_spec.rb'
         # ./spec/unit/outputs/redis_spec.rb:34:in `block in (root)'
         # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
     # ./spec/unit/outputs/redis_spec.rb:35:in `block in /home/travis/build/logstash-plugins/logstash-output-redis/spec/unit/outputs/redis_spec.rb'
     # ./spec/unit/outputs/redis_spec.rb:34:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/w
```
```
  1) LogStash::Outputs::Redis Redis#receive in batch mode should call buffer_receive
     Failure/Error: expect(redis).to receive(:buffer_receive).exactly(10000).times.and_call_original
     
       (<LogStash::Outputs::Redis key=>"thekey", data_type=>"list", batch=>true, batch_events=>50, id=>"redis_c5ebd5ad-51da-4633-8c5d-68756bd28aa8", enable_metric=>true, codec=><LogStash::Codecs::JSON id=>"json_0c16f495-39b0-45d4-97ec-ec2d1a0d8aba", enable_metric=>true, charset=>"UTF-8">, workers=>1, name=>"default", host=>["127.0.0.1"], shuffle_hosts=>true, port=>6379, db=>0, timeout=>5, batch_timeout=>5, reconnect_interval=>1, congestion_threshold=>0, congestion_interval=>1>).buffer_receive(*(any args))
           expected: 10000 times with any arguments
           received: 9999 times with any arguments
     # ./spec/unit/outputs/redis_spec.rb:28:in `(root)'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
Finished in 6.82 seconds (files took 2.93 seconds to load)
```

**Comment by guyboertje** [comment]
I am also seeing this ConcurrencyError when I modify the Redis `on_flush_error(e)` method to print out any errors. Moral of the story is be of how other threads can cause concurrent modifications to `message_received` when using RSpec 3.6+ Mock message expectations.
```
ConcurrencyError
Detected invalid array contents due to unsynchronized modifications with concurrent users
org/jruby/RubyArray.java:2486:in `map'
/Users/guy/.gem/jruby/2.3.3/gems/rspec-mocks-3.6.0/lib/rspec/mocks/proxy.rb:153:in `messages_arg_list'
/Users/guy/.gem/jruby/2.3.3/gems/rspec-mocks-3.6.0/lib/rspec/mocks/proxy.rb:181:in `message_received'
/Users/guy/.gem/jruby/2.3.3/gems/rspec-mocks-3.6.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
/Users/guy/.gem/jruby/2.3.3/gems/rspec-mocks-3.6.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
/Users/guy/.gem/jruby/2.3.3/gems/rspec-mocks-3.6.0/lib/rspec/mocks/method_double.rb:64:in `block in define_proxy_method'
/Users/guy/.gem/jruby/2.3.3/gems/stud-0.0.22/lib/stud/buffer.rb:222:in `block in buffer_flush'
org/jruby/RubyHash.java:1343:in `each'
/Users/guy/.gem/jruby/2.3.3/gems/stud-0.0.22/lib/stud/buffer.rb:217:in `buffer_flush'
/Users/guy/.gem/jruby/2.3.3/gems/stud-0.0.22/lib/stud/buffer.rb:112:in `block in buffer_initialize'
org/jruby/RubyKernel.java:1298:in `loop'
/Users/guy/.gem/jruby/2.3.3/gems/stud-0.0.22/lib/stud/buffer.rb:110:in `block in buffer_initialize'
```

**Comment by guyboertje** [comment]
I have detected the ways that this test can fail. It all boils down to the timing of the Timer thread calling `buffer_flush(:force => true)`. The `batch_timeout` is the default of 5 seconds and the test runs at 6+ seconds.

1. A ConcurrencyError (see comment above) is raised during the timed flush because the code is flushing. This error fails the no error expectation inside the 10000 times loop.
21. A ConcurrencyError is raised when the code tries to flush but the Timer thread is flushing. This causes the message expectation count to be less than 10000.
3. A timed flush causes a MockExpectationError to be raised by rspec when the `expect(redis).to receive(:flush).exactly(200).times` is exceeded. This error fails the no error expectation inside the 10000 times loop.

As the test sets up expectations on the **normal** buffer receive and flush mechanism and does not include provision for the Timer flush, my solution is to use a ridiculously large `batch_timeout` of 24 hours. This to prevent the Timer thread from flushing even on the slowest systems.

I **think** this fails now because RSpec 3.3+ reworked how message expectations were counted.
