### ISSUE TITLE
Output not working with password config option

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-redis#6]
When you use the password config option, it is not getting passed on to the redis connection. This is working on LS 1.5 beta1 and not on current master/RC1. Redis ruby gem was upgraded between the two versions so maybe its an issue with that. 

```
{:timestamp=>"2015-03-02T19:10:47.267000-0800", :message=>"Failed to send backlog of events to Redis", :identity=>"default", :exception=>#<Redis::CommandError: ERR invalid password>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.1/lib/redis/client.rb:113:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.1/lib/redis/client.rb:95:in `connect'", 
```

**Comment by untergeek** [comment]
The bug is apparently not with Redis, but somewhere inside Logstash:

```
   223: def connect
    224:   @current_host, @current_port = @host[@host_idx].split(':')
    225:   @host_idx = @host_idx + 1 >= @host.length ? 0 : @host_idx + 1
    226:
    227:   if not @current_port
    228:     @current_port = @port
    229:   end
    230:
    231:   params = {
    232:     :host => @current_host,
    233:     :port => @current_port,
    234:     :timeout => @timeout,
    235:     :db => @db
    236:   }
    237:   @logger.debug(params)
    238:
 => 239:   require "pry"; binding.pry
    240:   if @password
    241:     params[:password] = @password.value
    242:   end
    243:
    244:   Redis.new(params)
    245: end # def connect

[1] pry(#<LogStash::Outputs::Redis>)> @password.value
=> <password>
[1] pry(#<LogStash::Outputs::Redis>)> @password
=> <password>
[3] pry(#<LogStash::Outputs::Redis>)> @password.value.class
=> LogStash::Util::Password
```

`@password.value` should put the value of the password up, but it's not.  Instead, it's putting up another password object.

**Comment by talevy** [comment]
PR for fix: https://github.com/elasticsearch/logstash/pull/2767
